# -*- coding: utf-8 -*-
"""Image_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1koJot5LSgfbw7F8YQMWaJLprZxwh3v6X
"""

# !pip install diffusers --upgrade

# !pip install invisible_watermark transformers accelerate safetensors

"""# Final Model"""
from flask import Flask, send_file
from diffusers import StableDiffusionPipeline
import torch
import random
import io


app = Flask(__name__)

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float32)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")


def get_random_image():
  prompt ="  "
  num_steps = 20
  num_variations = 1
  prompt_guidance = 9
  dimensions = (400, 400) # (width, height) tuple
  random_seeds = [random.randint(0, 65000) for _ in range(num_variations)]

  image = pipe(prompt= num_variations * [prompt],
              num_inference_steps=num_steps,
              guidance_scale=prompt_guidance,
              height = dimensions[0],
              width = dimensions[1],
              generator = [torch.Generator().manual_seed(i) for i in random_seeds]
             ).images[0]
  
  
  img_io = io.BytesIO()
  image.save(img_io, 'PNG')
  img_io.seek(0)
    

  return img_io

@app.route('/generate_image', methods=['GET'])
def generate_image_route():
    # Example prompt
    # prompt = "A fantasy landscape with mountains and a river"
    img_io = get_random_image()
    return send_file(img_io, mimetype='image/png')

if __name__ == '__main__':
    app.run(port=5000)



# images = get_random_image()

# images[0].save("dog_image.png")